#!/bin/sh

BUILDDIR=$0/dist-newstyle/build/x86_64-linux/ghcjs-8.6.0.1/cat-site-0.1.0.0/x/site/build/site/site.jsexe

git checkout gh-pages || exit 1
rm -f all.min.js

cp "$BUILDDIR/all.js" .
cp "$BUILDDIR/all.js.externs" .
ccjs all.js --compilation-level=ADVANCED_OPTIMIZATIONS --jscomp_off=checkVars --externs=node --externs=all.js.externs > all.min.js
rm -f all.js all.js.externs

git add all.min.js
git commit -m 'Deployed site'
git push
git checkout -

