name:                cat
version:             0.1.0.0
github:              "Skyb0rg007/cat"
license:             BSD3
author:              "Skye Soss"
maintainer:          "skye.soss@tufts.edu"
copyright:           "2020 Skye Soss"

extra-source-files:
- README.md
- runtime.c

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cat#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- deepseq
- singlethongs
- recursion-schemes-ix
- constraints
- directory
- filepath
- megaparsec
# TODO
# - optics
- polysemy
- fmt
- optparse-applicative
- parser-combinators
- prettyprinter
- prettyprinter-ansi-terminal
- recursion-schemes
- text
- text-short
- unordered-containers
- mtl
- lens
- data-default

library:
  source-dirs: src

executables:
  cat:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cat

tests:
  cat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - hspec-discover
    dependencies:
    - hspec
    - QuickCheck
    - cat
